
// CREATE OR REPLACE PROCEDURE genre_insert_data(
//     "description" character varying,
//     "price" integer,
//     "property_type" character varying,
//     "property_condition" character varying, 
//      "property_address_city" character varying,
//    "property_address_street" character varying,
//     "property_address_num" integer, 
//      "property_floor" integer, 
//     "property_total_floors" integer ,
//     "num_of_rooms"	integer,
//     "is_on_pillars" boolean,
//    "num_of_parking" integer,
//    "num_of_balcony" integer,
//    "build_mr" integer,
//    "build_mr_total" integer,
//    "contact_name" character varying,
//    "contact_number_start" character varying,
//    "contact_number" character varying,
//    "mail" character varying,
//    "route" character varying,
//    "entry_date" timestamp,
//    "air_condition" boolean,
//    "shelter" boolean,
//    "garage" boolean,
//    "pandor" boolean,
//    "furniture" boolean,
//    "handicapped" boolean,
//    "elevator" boolean,
//    "tadiran" boolean,
//    "unit" boolean,
//    "renovated" boolean,
//    "kosher" boolean,
//    "boiler" boolean,
//    "bars" boolean,
//    "pic1" character varying,
//    "pic2" character varying,
//    "pic3" character varying,
//    "pic4" character varying,
//    "pic5" character varying,
//    "pic6" character varying,
//    "createdat" timestamp,
//    "updatedat" timestamp,
//    "userid" character varying
// )
// LANGUAGE SQL
// AS $$
// INSERT INTO products (
//     "description",
//     "price" ,
//     "property_type",
//     "property_condition", 
//      "property_address_city",
//    "property_address_street" ,
//     "property_address_num" , 
//      "property_floor" , 
//     "property_total_floors" ,
//     "num_of_rooms"	,
//     "is_on_pillars" ,
//    "num_of_parking" ,
//    "num_of_balcony" ,
//    "build_mr" ,
//    "build_mr_total",
//    "contact_name" ,
//    "contact_number_start" ,
//    "contact_number" ,
//    "mail" ,
//    "route" ,
//    "entry_date",
//    "air_condition",
//    "shelter" ,
//    "garage" ,
//    "pandor" ,
//    "furniture",
//    "handicapped",
//    "elevator",
//    "tadiran",
//    "unit" ,
//    "renovated",
//    "kosher",
//    "boiler",
//    "bars" ,
//    "pic1" ,
//    "pic2" ,
//    "pic3" ,
//    "pic4" ,
//    "pic5" ,
//    "pic6" ,
//    "createdat" ,
//    "updatedat" ,
//    "userid" 
// ) VALUES (
// "description",
//     "price" ,
//     "property_type",
//     "property_condition", 
//      "property_address_city",
//    "property_address_street" ,
//     "property_address_num" , 
//      "property_floor" , 
//     "property_total_floors" ,
//     "num_of_rooms"	,
//     "is_on_pillars" ,
//    "num_of_parking" ,
//    "num_of_balcony" ,
//    "build_mr" ,
//    "build_mr_total",
//    "contact_name" ,
//    "contact_number_start" ,
//    "contact_number" ,
//    "mail" ,
//    "route" ,
//    "entry_date",
//    "air_condition",
//    "shelter" ,
//    "garage" ,
//    "pandor" ,
//    "furniture",
//    "handicapped",
//    "elevator",
//    "tadiran",
//    "unit" ,
//    "renovated",
//    "kosher",
//    "boiler",
//    "bars" ,
//    "pic1" ,
//    "pic2" ,
//    "pic3" ,
//    "pic4" ,
//    "pic5" ,
//    "pic6" ,
//    "createdat" ,
//    "updatedat" ,
//    "userid"
// );
// $$;
